In [4]:
import numpy as np

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

In [6]:
x = np.arange(10).reshape(-1,1)
y = np.array([0,1,0,0,1,1,1,1,1,1])
print(x)
print(y)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[0 1 0 0 1 1 1 1 1 1]


In [7]:
# create model

model = LogisticRegression(solver='liblinear', C = 10.0, random_state = 0)

In [8]:
model.fit(x,y)

LogisticRegression(C=10.0, random_state=0, solver='liblinear')

In [14]:
# Evaluate the model

p_pred = model.predict_proba(x)
p_pred

array([[0.81999686, 0.18000314],
       [0.69272057, 0.30727943],
       [0.52732579, 0.47267421],
       [0.35570732, 0.64429268],
       [0.21458576, 0.78541424],
       [0.11910229, 0.88089771],
       [0.06271329, 0.93728671],
       [0.03205032, 0.96794968],
       [0.0161218 , 0.9838782 ],
       [0.00804372, 0.99195628]])

In [15]:
y_pred = model.predict(x)
y_pred

array([0, 0, 0, 1, 1, 1, 1, 1, 1, 1])

In [16]:
score = model.score(x,y)
score

0.8

In [17]:
conf_mat = confusion_matrix(y,y_pred)
conf_mat

array([[2, 1],
       [1, 6]])

In [22]:
report = classification_report(y,y_pred)
print(report,sep = '\n')

              precision    recall  f1-score   support

           0       0.67      0.67      0.67         3
           1       0.86      0.86      0.86         7

    accuracy                           0.80        10
   macro avg       0.76      0.76      0.76        10
weighted avg       0.80      0.80      0.80        10



In [19]:
model.intercept_

array([-1.51632619])

In [20]:
model.coef_

array([[0.703457]])

In [21]:
print(y)
print(y_pred)

[0 1 0 0 1 1 1 1 1 1]
[0 0 0 1 1 1 1 1 1 1]
